// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yhglobalcoupon.proto

package com.yhglobal.gongxiao.accountmanage.microservice;

public final class YhglobalCouponServiceStructure {
  private YhglobalCouponServiceStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenerateYhglobalCouponLedgerReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GenerateYhglobalCouponLedgerReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    boolean hasRpcHeader();
    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader();
    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder();

    /**
     * <code>int64 projectId = 2;</code>
     */
    long getProjectId();

    /**
     * <code>string currencyCode = 3;</code>
     */
    String getCurrencyCode();
    /**
     * <code>string currencyCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyCodeBytes();

    /**
     * <code>string brandOrderNo = 4;</code>
     */
    String getBrandOrderNo();
    /**
     * <code>string brandOrderNo = 4;</code>
     */
    com.google.protobuf.ByteString
        getBrandOrderNoBytes();

    /**
     * <code>string purchaseOrderNo = 5;</code>
     */
    String getPurchaseOrderNo();
    /**
     * <code>string purchaseOrderNo = 5;</code>
     */
    com.google.protobuf.ByteString
        getPurchaseOrderNoBytes();

    /**
     * <code>string purchaseTime = 6;</code>
     */
    String getPurchaseTime();
    /**
     * <code>string purchaseTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getPurchaseTimeBytes();

    /**
     * <code>int64 purchaseShouldPayAmount = 7;</code>
     */
    long getPurchaseShouldPayAmount();

    /**
     * <pre>
     * Byte couponType, Long couponRatio project.getProjectName() project.getSupplierId()  project.getSupplierName()
     * </pre>
     *
     * <code>int32 couponType = 8;</code>
     */
    int getCouponType();

    /**
     * <code>int64 couponRatio = 9;</code>
     */
    long getCouponRatio();

    /**
     * <code>string projectName = 10;</code>
     */
    String getProjectName();
    /**
     * <code>string projectName = 10;</code>
     */
    com.google.protobuf.ByteString
        getProjectNameBytes();

    /**
     * <code>int64 supplierId = 11;</code>
     */
    long getSupplierId();

    /**
     * <code>string supplierName = 12;</code>
     */
    String getSupplierName();
    /**
     * <code>string supplierName = 12;</code>
     */
    com.google.protobuf.ByteString
        getSupplierNameBytes();

    /**
     * <code>string tablePrefix = 13;</code>
     */
    String getTablePrefix();
    /**
     * <code>string tablePrefix = 13;</code>
     */
    com.google.protobuf.ByteString
        getTablePrefixBytes();
  }
  /**
   * Protobuf type {@code GenerateYhglobalCouponLedgerReq}
   */
  public  static final class GenerateYhglobalCouponLedgerReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GenerateYhglobalCouponLedgerReq)
      GenerateYhglobalCouponLedgerReqOrBuilder {
    // Use GenerateYhglobalCouponLedgerReq.newBuilder() to construct.
    private GenerateYhglobalCouponLedgerReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenerateYhglobalCouponLedgerReq() {
      projectId_ = 0L;
      currencyCode_ = "";
      brandOrderNo_ = "";
      purchaseOrderNo_ = "";
      purchaseTime_ = "";
      purchaseShouldPayAmount_ = 0L;
      couponType_ = 0;
      couponRatio_ = 0L;
      projectName_ = "";
      supplierId_ = 0L;
      supplierName_ = "";
      tablePrefix_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GenerateYhglobalCouponLedgerReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder subBuilder = null;
              if (rpcHeader_ != null) {
                subBuilder = rpcHeader_.toBuilder();
              }
              rpcHeader_ = input.readMessage(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcHeader_);
                rpcHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              projectId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              currencyCode_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              brandOrderNo_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              purchaseOrderNo_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              purchaseTime_ = s;
              break;
            }
            case 56: {

              purchaseShouldPayAmount_ = input.readInt64();
              break;
            }
            case 64: {

              couponType_ = input.readInt32();
              break;
            }
            case 72: {

              couponRatio_ = input.readInt64();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              projectName_ = s;
              break;
            }
            case 88: {

              supplierId_ = input.readInt64();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              supplierName_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              tablePrefix_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GenerateYhglobalCouponLedgerReq.class, Builder.class);
    }

    public static final int RPCHEADER_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_;
    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public boolean hasRpcHeader() {
      return rpcHeader_ != null;
    }
    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
      return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
    }
    /**
     * <pre>
     * 需求参数精简
     * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
     * </pre>
     *
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
      return getRpcHeader();
    }

    public static final int PROJECTID_FIELD_NUMBER = 2;
    private long projectId_;
    /**
     * <code>int64 projectId = 2;</code>
     */
    public long getProjectId() {
      return projectId_;
    }

    public static final int CURRENCYCODE_FIELD_NUMBER = 3;
    private volatile Object currencyCode_;
    /**
     * <code>string currencyCode = 3;</code>
     */
    public String getCurrencyCode() {
      Object ref = currencyCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRANDORDERNO_FIELD_NUMBER = 4;
    private volatile Object brandOrderNo_;
    /**
     * <code>string brandOrderNo = 4;</code>
     */
    public String getBrandOrderNo() {
      Object ref = brandOrderNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brandOrderNo_ = s;
        return s;
      }
    }
    /**
     * <code>string brandOrderNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrandOrderNoBytes() {
      Object ref = brandOrderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brandOrderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PURCHASEORDERNO_FIELD_NUMBER = 5;
    private volatile Object purchaseOrderNo_;
    /**
     * <code>string purchaseOrderNo = 5;</code>
     */
    public String getPurchaseOrderNo() {
      Object ref = purchaseOrderNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        purchaseOrderNo_ = s;
        return s;
      }
    }
    /**
     * <code>string purchaseOrderNo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPurchaseOrderNoBytes() {
      Object ref = purchaseOrderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        purchaseOrderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PURCHASETIME_FIELD_NUMBER = 6;
    private volatile Object purchaseTime_;
    /**
     * <code>string purchaseTime = 6;</code>
     */
    public String getPurchaseTime() {
      Object ref = purchaseTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        purchaseTime_ = s;
        return s;
      }
    }
    /**
     * <code>string purchaseTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPurchaseTimeBytes() {
      Object ref = purchaseTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        purchaseTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PURCHASESHOULDPAYAMOUNT_FIELD_NUMBER = 7;
    private long purchaseShouldPayAmount_;
    /**
     * <code>int64 purchaseShouldPayAmount = 7;</code>
     */
    public long getPurchaseShouldPayAmount() {
      return purchaseShouldPayAmount_;
    }

    public static final int COUPONTYPE_FIELD_NUMBER = 8;
    private int couponType_;
    /**
     * <pre>
     * Byte couponType, Long couponRatio project.getProjectName() project.getSupplierId()  project.getSupplierName()
     * </pre>
     *
     * <code>int32 couponType = 8;</code>
     */
    public int getCouponType() {
      return couponType_;
    }

    public static final int COUPONRATIO_FIELD_NUMBER = 9;
    private long couponRatio_;
    /**
     * <code>int64 couponRatio = 9;</code>
     */
    public long getCouponRatio() {
      return couponRatio_;
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 10;
    private volatile Object projectName_;
    /**
     * <code>string projectName = 10;</code>
     */
    public String getProjectName() {
      Object ref = projectName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      }
    }
    /**
     * <code>string projectName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      Object ref = projectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUPPLIERID_FIELD_NUMBER = 11;
    private long supplierId_;
    /**
     * <code>int64 supplierId = 11;</code>
     */
    public long getSupplierId() {
      return supplierId_;
    }

    public static final int SUPPLIERNAME_FIELD_NUMBER = 12;
    private volatile Object supplierName_;
    /**
     * <code>string supplierName = 12;</code>
     */
    public String getSupplierName() {
      Object ref = supplierName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        supplierName_ = s;
        return s;
      }
    }
    /**
     * <code>string supplierName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getSupplierNameBytes() {
      Object ref = supplierName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        supplierName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLEPREFIX_FIELD_NUMBER = 13;
    private volatile Object tablePrefix_;
    /**
     * <code>string tablePrefix = 13;</code>
     */
    public String getTablePrefix() {
      Object ref = tablePrefix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tablePrefix_ = s;
        return s;
      }
    }
    /**
     * <code>string tablePrefix = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTablePrefixBytes() {
      Object ref = tablePrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tablePrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcHeader_ != null) {
        output.writeMessage(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        output.writeInt64(2, projectId_);
      }
      if (!getCurrencyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, currencyCode_);
      }
      if (!getBrandOrderNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, brandOrderNo_);
      }
      if (!getPurchaseOrderNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, purchaseOrderNo_);
      }
      if (!getPurchaseTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, purchaseTime_);
      }
      if (purchaseShouldPayAmount_ != 0L) {
        output.writeInt64(7, purchaseShouldPayAmount_);
      }
      if (couponType_ != 0) {
        output.writeInt32(8, couponType_);
      }
      if (couponRatio_ != 0L) {
        output.writeInt64(9, couponRatio_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, projectName_);
      }
      if (supplierId_ != 0L) {
        output.writeInt64(11, supplierId_);
      }
      if (!getSupplierNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, supplierName_);
      }
      if (!getTablePrefixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, tablePrefix_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, projectId_);
      }
      if (!getCurrencyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, currencyCode_);
      }
      if (!getBrandOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, brandOrderNo_);
      }
      if (!getPurchaseOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, purchaseOrderNo_);
      }
      if (!getPurchaseTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, purchaseTime_);
      }
      if (purchaseShouldPayAmount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, purchaseShouldPayAmount_);
      }
      if (couponType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, couponType_);
      }
      if (couponRatio_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, couponRatio_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, projectName_);
      }
      if (supplierId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, supplierId_);
      }
      if (!getSupplierNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, supplierName_);
      }
      if (!getTablePrefixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, tablePrefix_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GenerateYhglobalCouponLedgerReq)) {
        return super.equals(obj);
      }
      GenerateYhglobalCouponLedgerReq other = (GenerateYhglobalCouponLedgerReq) obj;

      boolean result = true;
      result = result && (hasRpcHeader() == other.hasRpcHeader());
      if (hasRpcHeader()) {
        result = result && getRpcHeader()
            .equals(other.getRpcHeader());
      }
      result = result && (getProjectId()
          == other.getProjectId());
      result = result && getCurrencyCode()
          .equals(other.getCurrencyCode());
      result = result && getBrandOrderNo()
          .equals(other.getBrandOrderNo());
      result = result && getPurchaseOrderNo()
          .equals(other.getPurchaseOrderNo());
      result = result && getPurchaseTime()
          .equals(other.getPurchaseTime());
      result = result && (getPurchaseShouldPayAmount()
          == other.getPurchaseShouldPayAmount());
      result = result && (getCouponType()
          == other.getCouponType());
      result = result && (getCouponRatio()
          == other.getCouponRatio());
      result = result && getProjectName()
          .equals(other.getProjectName());
      result = result && (getSupplierId()
          == other.getSupplierId());
      result = result && getSupplierName()
          .equals(other.getSupplierName());
      result = result && getTablePrefix()
          .equals(other.getTablePrefix());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRpcHeader()) {
        hash = (37 * hash) + RPCHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getRpcHeader().hashCode();
      }
      hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProjectId());
      hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyCode().hashCode();
      hash = (37 * hash) + BRANDORDERNO_FIELD_NUMBER;
      hash = (53 * hash) + getBrandOrderNo().hashCode();
      hash = (37 * hash) + PURCHASEORDERNO_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseOrderNo().hashCode();
      hash = (37 * hash) + PURCHASETIME_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseTime().hashCode();
      hash = (37 * hash) + PURCHASESHOULDPAYAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPurchaseShouldPayAmount());
      hash = (37 * hash) + COUPONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCouponType();
      hash = (37 * hash) + COUPONRATIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCouponRatio());
      hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProjectName().hashCode();
      hash = (37 * hash) + SUPPLIERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSupplierId());
      hash = (37 * hash) + SUPPLIERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSupplierName().hashCode();
      hash = (37 * hash) + TABLEPREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getTablePrefix().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GenerateYhglobalCouponLedgerReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GenerateYhglobalCouponLedgerReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GenerateYhglobalCouponLedgerReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GenerateYhglobalCouponLedgerReq)
        GenerateYhglobalCouponLedgerReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GenerateYhglobalCouponLedgerReq.class, Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.accountmanage.microservice.YhglobalCouponServiceStructure.GenerateYhglobalCouponLedgerReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }
        projectId_ = 0L;

        currencyCode_ = "";

        brandOrderNo_ = "";

        purchaseOrderNo_ = "";

        purchaseTime_ = "";

        purchaseShouldPayAmount_ = 0L;

        couponType_ = 0;

        couponRatio_ = 0L;

        projectName_ = "";

        supplierId_ = 0L;

        supplierName_ = "";

        tablePrefix_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerReq_descriptor;
      }

      public GenerateYhglobalCouponLedgerReq getDefaultInstanceForType() {
        return GenerateYhglobalCouponLedgerReq.getDefaultInstance();
      }

      public GenerateYhglobalCouponLedgerReq build() {
        GenerateYhglobalCouponLedgerReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GenerateYhglobalCouponLedgerReq buildPartial() {
        GenerateYhglobalCouponLedgerReq result = new GenerateYhglobalCouponLedgerReq(this);
        if (rpcHeaderBuilder_ == null) {
          result.rpcHeader_ = rpcHeader_;
        } else {
          result.rpcHeader_ = rpcHeaderBuilder_.build();
        }
        result.projectId_ = projectId_;
        result.currencyCode_ = currencyCode_;
        result.brandOrderNo_ = brandOrderNo_;
        result.purchaseOrderNo_ = purchaseOrderNo_;
        result.purchaseTime_ = purchaseTime_;
        result.purchaseShouldPayAmount_ = purchaseShouldPayAmount_;
        result.couponType_ = couponType_;
        result.couponRatio_ = couponRatio_;
        result.projectName_ = projectName_;
        result.supplierId_ = supplierId_;
        result.supplierName_ = supplierName_;
        result.tablePrefix_ = tablePrefix_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GenerateYhglobalCouponLedgerReq) {
          return mergeFrom((GenerateYhglobalCouponLedgerReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GenerateYhglobalCouponLedgerReq other) {
        if (other == GenerateYhglobalCouponLedgerReq.getDefaultInstance()) return this;
        if (other.hasRpcHeader()) {
          mergeRpcHeader(other.getRpcHeader());
        }
        if (other.getProjectId() != 0L) {
          setProjectId(other.getProjectId());
        }
        if (!other.getCurrencyCode().isEmpty()) {
          currencyCode_ = other.currencyCode_;
          onChanged();
        }
        if (!other.getBrandOrderNo().isEmpty()) {
          brandOrderNo_ = other.brandOrderNo_;
          onChanged();
        }
        if (!other.getPurchaseOrderNo().isEmpty()) {
          purchaseOrderNo_ = other.purchaseOrderNo_;
          onChanged();
        }
        if (!other.getPurchaseTime().isEmpty()) {
          purchaseTime_ = other.purchaseTime_;
          onChanged();
        }
        if (other.getPurchaseShouldPayAmount() != 0L) {
          setPurchaseShouldPayAmount(other.getPurchaseShouldPayAmount());
        }
        if (other.getCouponType() != 0) {
          setCouponType(other.getCouponType());
        }
        if (other.getCouponRatio() != 0L) {
          setCouponRatio(other.getCouponRatio());
        }
        if (!other.getProjectName().isEmpty()) {
          projectName_ = other.projectName_;
          onChanged();
        }
        if (other.getSupplierId() != 0L) {
          setSupplierId(other.getSupplierId());
        }
        if (!other.getSupplierName().isEmpty()) {
          supplierName_ = other.supplierName_;
          onChanged();
        }
        if (!other.getTablePrefix().isEmpty()) {
          tablePrefix_ = other.tablePrefix_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GenerateYhglobalCouponLedgerReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GenerateYhglobalCouponLedgerReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> rpcHeaderBuilder_;
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public boolean hasRpcHeader() {
        return rpcHeaderBuilder_ != null || rpcHeader_ != null;
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        } else {
          return rpcHeaderBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcHeader_ = value;
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder builderForValue) {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = builderForValue.build();
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder mergeRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (rpcHeader_ != null) {
            rpcHeader_ =
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.newBuilder(rpcHeader_).mergeFrom(value).buildPartial();
          } else {
            rpcHeader_ = value;
          }
          onChanged();
        } else {
          rpcHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder clearRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
          onChanged();
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder getRpcHeaderBuilder() {
        
        onChanged();
        return getRpcHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
        if (rpcHeaderBuilder_ != null) {
          return rpcHeaderBuilder_.getMessageOrBuilder();
        } else {
          return rpcHeader_ == null ?
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        }
      }
      /**
       * <pre>
       * 需求参数精简
       * projectId currencyCode SupplierOrderNo PurchaseOrderNo PurchaseTime从 PurchaseShouldPayAmount
       * </pre>
       *
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> 
          getRpcHeaderFieldBuilder() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder>(
                  getRpcHeader(),
                  getParentForChildren(),
                  isClean());
          rpcHeader_ = null;
        }
        return rpcHeaderBuilder_;
      }

      private long projectId_ ;
      /**
       * <code>int64 projectId = 2;</code>
       */
      public long getProjectId() {
        return projectId_;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder setProjectId(long value) {
        
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = 0L;
        onChanged();
        return this;
      }

      private Object currencyCode_ = "";
      /**
       * <code>string currencyCode = 3;</code>
       */
      public String getCurrencyCode() {
        Object ref = currencyCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          currencyCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string currencyCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyCodeBytes() {
        Object ref = currencyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          currencyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyCode = 3;</code>
       */
      public Builder setCurrencyCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 3;</code>
       */
      public Builder clearCurrencyCode() {
        
        currencyCode_ = getDefaultInstance().getCurrencyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 3;</code>
       */
      public Builder setCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyCode_ = value;
        onChanged();
        return this;
      }

      private Object brandOrderNo_ = "";
      /**
       * <code>string brandOrderNo = 4;</code>
       */
      public String getBrandOrderNo() {
        Object ref = brandOrderNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brandOrderNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string brandOrderNo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBrandOrderNoBytes() {
        Object ref = brandOrderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brandOrderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brandOrderNo = 4;</code>
       */
      public Builder setBrandOrderNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brandOrderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brandOrderNo = 4;</code>
       */
      public Builder clearBrandOrderNo() {
        
        brandOrderNo_ = getDefaultInstance().getBrandOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>string brandOrderNo = 4;</code>
       */
      public Builder setBrandOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brandOrderNo_ = value;
        onChanged();
        return this;
      }

      private Object purchaseOrderNo_ = "";
      /**
       * <code>string purchaseOrderNo = 5;</code>
       */
      public String getPurchaseOrderNo() {
        Object ref = purchaseOrderNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          purchaseOrderNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string purchaseOrderNo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPurchaseOrderNoBytes() {
        Object ref = purchaseOrderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          purchaseOrderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string purchaseOrderNo = 5;</code>
       */
      public Builder setPurchaseOrderNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        purchaseOrderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string purchaseOrderNo = 5;</code>
       */
      public Builder clearPurchaseOrderNo() {
        
        purchaseOrderNo_ = getDefaultInstance().getPurchaseOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>string purchaseOrderNo = 5;</code>
       */
      public Builder setPurchaseOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        purchaseOrderNo_ = value;
        onChanged();
        return this;
      }

      private Object purchaseTime_ = "";
      /**
       * <code>string purchaseTime = 6;</code>
       */
      public String getPurchaseTime() {
        Object ref = purchaseTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          purchaseTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string purchaseTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPurchaseTimeBytes() {
        Object ref = purchaseTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          purchaseTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string purchaseTime = 6;</code>
       */
      public Builder setPurchaseTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        purchaseTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string purchaseTime = 6;</code>
       */
      public Builder clearPurchaseTime() {
        
        purchaseTime_ = getDefaultInstance().getPurchaseTime();
        onChanged();
        return this;
      }
      /**
       * <code>string purchaseTime = 6;</code>
       */
      public Builder setPurchaseTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        purchaseTime_ = value;
        onChanged();
        return this;
      }

      private long purchaseShouldPayAmount_ ;
      /**
       * <code>int64 purchaseShouldPayAmount = 7;</code>
       */
      public long getPurchaseShouldPayAmount() {
        return purchaseShouldPayAmount_;
      }
      /**
       * <code>int64 purchaseShouldPayAmount = 7;</code>
       */
      public Builder setPurchaseShouldPayAmount(long value) {
        
        purchaseShouldPayAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 purchaseShouldPayAmount = 7;</code>
       */
      public Builder clearPurchaseShouldPayAmount() {
        
        purchaseShouldPayAmount_ = 0L;
        onChanged();
        return this;
      }

      private int couponType_ ;
      /**
       * <pre>
       * Byte couponType, Long couponRatio project.getProjectName() project.getSupplierId()  project.getSupplierName()
       * </pre>
       *
       * <code>int32 couponType = 8;</code>
       */
      public int getCouponType() {
        return couponType_;
      }
      /**
       * <pre>
       * Byte couponType, Long couponRatio project.getProjectName() project.getSupplierId()  project.getSupplierName()
       * </pre>
       *
       * <code>int32 couponType = 8;</code>
       */
      public Builder setCouponType(int value) {
        
        couponType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Byte couponType, Long couponRatio project.getProjectName() project.getSupplierId()  project.getSupplierName()
       * </pre>
       *
       * <code>int32 couponType = 8;</code>
       */
      public Builder clearCouponType() {
        
        couponType_ = 0;
        onChanged();
        return this;
      }

      private long couponRatio_ ;
      /**
       * <code>int64 couponRatio = 9;</code>
       */
      public long getCouponRatio() {
        return couponRatio_;
      }
      /**
       * <code>int64 couponRatio = 9;</code>
       */
      public Builder setCouponRatio(long value) {
        
        couponRatio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 couponRatio = 9;</code>
       */
      public Builder clearCouponRatio() {
        
        couponRatio_ = 0L;
        onChanged();
        return this;
      }

      private Object projectName_ = "";
      /**
       * <code>string projectName = 10;</code>
       */
      public String getProjectName() {
        Object ref = projectName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          projectName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string projectName = 10;</code>
       */
      public com.google.protobuf.ByteString
          getProjectNameBytes() {
        Object ref = projectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          projectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string projectName = 10;</code>
       */
      public Builder setProjectName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 10;</code>
       */
      public Builder clearProjectName() {
        
        projectName_ = getDefaultInstance().getProjectName();
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 10;</code>
       */
      public Builder setProjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectName_ = value;
        onChanged();
        return this;
      }

      private long supplierId_ ;
      /**
       * <code>int64 supplierId = 11;</code>
       */
      public long getSupplierId() {
        return supplierId_;
      }
      /**
       * <code>int64 supplierId = 11;</code>
       */
      public Builder setSupplierId(long value) {
        
        supplierId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 supplierId = 11;</code>
       */
      public Builder clearSupplierId() {
        
        supplierId_ = 0L;
        onChanged();
        return this;
      }

      private Object supplierName_ = "";
      /**
       * <code>string supplierName = 12;</code>
       */
      public String getSupplierName() {
        Object ref = supplierName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          supplierName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string supplierName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSupplierNameBytes() {
        Object ref = supplierName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          supplierName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string supplierName = 12;</code>
       */
      public Builder setSupplierName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        supplierName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string supplierName = 12;</code>
       */
      public Builder clearSupplierName() {
        
        supplierName_ = getDefaultInstance().getSupplierName();
        onChanged();
        return this;
      }
      /**
       * <code>string supplierName = 12;</code>
       */
      public Builder setSupplierNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        supplierName_ = value;
        onChanged();
        return this;
      }

      private Object tablePrefix_ = "";
      /**
       * <code>string tablePrefix = 13;</code>
       */
      public String getTablePrefix() {
        Object ref = tablePrefix_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tablePrefix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tablePrefix = 13;</code>
       */
      public com.google.protobuf.ByteString
          getTablePrefixBytes() {
        Object ref = tablePrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tablePrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tablePrefix = 13;</code>
       */
      public Builder setTablePrefix(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tablePrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tablePrefix = 13;</code>
       */
      public Builder clearTablePrefix() {
        
        tablePrefix_ = getDefaultInstance().getTablePrefix();
        onChanged();
        return this;
      }
      /**
       * <code>string tablePrefix = 13;</code>
       */
      public Builder setTablePrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tablePrefix_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GenerateYhglobalCouponLedgerReq)
    }

    // @@protoc_insertion_point(class_scope:GenerateYhglobalCouponLedgerReq)
    private static final GenerateYhglobalCouponLedgerReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GenerateYhglobalCouponLedgerReq();
    }

    public static GenerateYhglobalCouponLedgerReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenerateYhglobalCouponLedgerReq>
        PARSER = new com.google.protobuf.AbstractParser<GenerateYhglobalCouponLedgerReq>() {
      public GenerateYhglobalCouponLedgerReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenerateYhglobalCouponLedgerReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenerateYhglobalCouponLedgerReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GenerateYhglobalCouponLedgerReq> getParserForType() {
      return PARSER;
    }

    public GenerateYhglobalCouponLedgerReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenerateYhglobalCouponLedgerRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GenerateYhglobalCouponLedgerResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 returnCode = 1;</code>
     */
    int getReturnCode();

    /**
     * <pre>
     *若调用不成功 错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    String getMsg();
    /**
     * <pre>
     *若调用不成功 错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code GenerateYhglobalCouponLedgerResp}
   */
  public  static final class GenerateYhglobalCouponLedgerResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GenerateYhglobalCouponLedgerResp)
      GenerateYhglobalCouponLedgerRespOrBuilder {
    // Use GenerateYhglobalCouponLedgerResp.newBuilder() to construct.
    private GenerateYhglobalCouponLedgerResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenerateYhglobalCouponLedgerResp() {
      returnCode_ = 0;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GenerateYhglobalCouponLedgerResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              returnCode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GenerateYhglobalCouponLedgerResp.class, Builder.class);
    }

    public static final int RETURNCODE_FIELD_NUMBER = 1;
    private int returnCode_;
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 returnCode = 1;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <pre>
     *若调用不成功 错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *若调用不成功 错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (returnCode_ != 0) {
        output.writeInt32(1, returnCode_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (returnCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, returnCode_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GenerateYhglobalCouponLedgerResp)) {
        return super.equals(obj);
      }
      GenerateYhglobalCouponLedgerResp other = (GenerateYhglobalCouponLedgerResp) obj;

      boolean result = true;
      result = result && (getReturnCode()
          == other.getReturnCode());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
      hash = (53 * hash) + getReturnCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GenerateYhglobalCouponLedgerResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GenerateYhglobalCouponLedgerResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GenerateYhglobalCouponLedgerResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GenerateYhglobalCouponLedgerResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GenerateYhglobalCouponLedgerResp)
        GenerateYhglobalCouponLedgerRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GenerateYhglobalCouponLedgerResp.class, Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.accountmanage.microservice.YhglobalCouponServiceStructure.GenerateYhglobalCouponLedgerResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        returnCode_ = 0;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YhglobalCouponServiceStructure.internal_static_GenerateYhglobalCouponLedgerResp_descriptor;
      }

      public GenerateYhglobalCouponLedgerResp getDefaultInstanceForType() {
        return GenerateYhglobalCouponLedgerResp.getDefaultInstance();
      }

      public GenerateYhglobalCouponLedgerResp build() {
        GenerateYhglobalCouponLedgerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GenerateYhglobalCouponLedgerResp buildPartial() {
        GenerateYhglobalCouponLedgerResp result = new GenerateYhglobalCouponLedgerResp(this);
        result.returnCode_ = returnCode_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GenerateYhglobalCouponLedgerResp) {
          return mergeFrom((GenerateYhglobalCouponLedgerResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GenerateYhglobalCouponLedgerResp other) {
        if (other == GenerateYhglobalCouponLedgerResp.getDefaultInstance()) return this;
        if (other.getReturnCode() != 0) {
          setReturnCode(other.getReturnCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GenerateYhglobalCouponLedgerResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GenerateYhglobalCouponLedgerResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int returnCode_ ;
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public int getReturnCode() {
        return returnCode_;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public Builder setReturnCode(int value) {
        
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public Builder clearReturnCode() {
        
        returnCode_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       *若调用不成功 错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *若调用不成功 错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *若调用不成功 错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *若调用不成功 错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *若调用不成功 错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GenerateYhglobalCouponLedgerResp)
    }

    // @@protoc_insertion_point(class_scope:GenerateYhglobalCouponLedgerResp)
    private static final GenerateYhglobalCouponLedgerResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GenerateYhglobalCouponLedgerResp();
    }

    public static GenerateYhglobalCouponLedgerResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenerateYhglobalCouponLedgerResp>
        PARSER = new com.google.protobuf.AbstractParser<GenerateYhglobalCouponLedgerResp>() {
      public GenerateYhglobalCouponLedgerResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenerateYhglobalCouponLedgerResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenerateYhglobalCouponLedgerResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GenerateYhglobalCouponLedgerResp> getParserForType() {
      return PARSER;
    }

    public GenerateYhglobalCouponLedgerResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateYhglobalCouponLedgerReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateYhglobalCouponLedgerReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateYhglobalCouponLedgerResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateYhglobalCouponLedgerResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024yhglobalcoupon.proto\032\037gongxiao.global." +
      "structure.proto\"\314\002\n\037GenerateYhglobalCoup" +
      "onLedgerReq\022\035\n\trpcHeader\030\001 \001(\0132\n.RpcHead" +
      "er\022\021\n\tprojectId\030\002 \001(\003\022\024\n\014currencyCode\030\003 " +
      "\001(\t\022\024\n\014brandOrderNo\030\004 \001(\t\022\027\n\017purchaseOrd" +
      "erNo\030\005 \001(\t\022\024\n\014purchaseTime\030\006 \001(\t\022\037\n\027purc" +
      "haseShouldPayAmount\030\007 \001(\003\022\022\n\ncouponType\030" +
      "\010 \001(\005\022\023\n\013couponRatio\030\t \001(\003\022\023\n\013projectNam" +
      "e\030\n \001(\t\022\022\n\nsupplierId\030\013 \001(\003\022\024\n\014supplierN" +
      "ame\030\014 \001(\t\022\023\n\013tablePrefix\030\r \001(\t\"C\n Genera",
      "teYhglobalCouponLedgerResp\022\022\n\nreturnCode" +
      "\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t2~\n\025YhglobalCouponSer" +
      "vice\022e\n\034generateYhglobalCouponLedger\022 .G" +
      "enerateYhglobalCouponLedgerReq\032!.Generat" +
      "eYhglobalCouponLedgerResp\"\000BR\n0com.yhglo" +
      "bal.gongxiao.accountmanage.microserviceB" +
      "\036YhglobalCouponServiceStructureb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor(),
        }, assigner);
    internal_static_GenerateYhglobalCouponLedgerReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GenerateYhglobalCouponLedgerReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateYhglobalCouponLedgerReq_descriptor,
        new String[] { "RpcHeader", "ProjectId", "CurrencyCode", "BrandOrderNo", "PurchaseOrderNo", "PurchaseTime", "PurchaseShouldPayAmount", "CouponType", "CouponRatio", "ProjectName", "SupplierId", "SupplierName", "TablePrefix", });
    internal_static_GenerateYhglobalCouponLedgerResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GenerateYhglobalCouponLedgerResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateYhglobalCouponLedgerResp_descriptor,
        new String[] { "ReturnCode", "Msg", });
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
