// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: productinventory180age.proto

package com.yhglobal.gongxiao.inventory.productinventory180age.microservice;

public final class ProductInventory180AgeStructure {
  private ProductInventory180AgeStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetProductInventory180AgeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetProductInventory180AgeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    boolean hasRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder();

    /**
     * <code>int64 projectId = 2;</code>
     */
    long getProjectId();
  }
  /**
   * Protobuf type {@code GetProductInventory180AgeRequest}
   */
  public  static final class GetProductInventory180AgeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetProductInventory180AgeRequest)
      GetProductInventory180AgeRequestOrBuilder {
    // Use GetProductInventory180AgeRequest.newBuilder() to construct.
    private GetProductInventory180AgeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProductInventory180AgeRequest() {
      projectId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetProductInventory180AgeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder subBuilder = null;
              if (rpcHeader_ != null) {
                subBuilder = rpcHeader_.toBuilder();
              }
              rpcHeader_ = input.readMessage(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcHeader_);
                rpcHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              projectId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.Builder.class);
    }

    public static final int RPCHEADER_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_;
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public boolean hasRpcHeader() {
      return rpcHeader_ != null;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
      return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
      return getRpcHeader();
    }

    public static final int PROJECTID_FIELD_NUMBER = 2;
    private long projectId_;
    /**
     * <code>int64 projectId = 2;</code>
     */
    public long getProjectId() {
      return projectId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcHeader_ != null) {
        output.writeMessage(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        output.writeInt64(2, projectId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, projectId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest other = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest) obj;

      boolean result = true;
      result = result && (hasRpcHeader() == other.hasRpcHeader());
      if (hasRpcHeader()) {
        result = result && getRpcHeader()
            .equals(other.getRpcHeader());
      }
      result = result && (getProjectId()
          == other.getProjectId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRpcHeader()) {
        hash = (37 * hash) + RPCHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getRpcHeader().hashCode();
      }
      hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProjectId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetProductInventory180AgeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetProductInventory180AgeRequest)
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }
        projectId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRequest_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest build() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest buildPartial() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest result = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest(this);
        if (rpcHeaderBuilder_ == null) {
          result.rpcHeader_ = rpcHeader_;
        } else {
          result.rpcHeader_ = rpcHeaderBuilder_.build();
        }
        result.projectId_ = projectId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest other) {
        if (other == com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest.getDefaultInstance()) return this;
        if (other.hasRpcHeader()) {
          mergeRpcHeader(other.getRpcHeader());
        }
        if (other.getProjectId() != 0L) {
          setProjectId(other.getProjectId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> rpcHeaderBuilder_;
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public boolean hasRpcHeader() {
        return rpcHeaderBuilder_ != null || rpcHeader_ != null;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        } else {
          return rpcHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcHeader_ = value;
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder builderForValue) {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = builderForValue.build();
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder mergeRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (rpcHeader_ != null) {
            rpcHeader_ =
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.newBuilder(rpcHeader_).mergeFrom(value).buildPartial();
          } else {
            rpcHeader_ = value;
          }
          onChanged();
        } else {
          rpcHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder clearRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
          onChanged();
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder getRpcHeaderBuilder() {
        
        onChanged();
        return getRpcHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
        if (rpcHeaderBuilder_ != null) {
          return rpcHeaderBuilder_.getMessageOrBuilder();
        } else {
          return rpcHeader_ == null ?
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> 
          getRpcHeaderFieldBuilder() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder>(
                  getRpcHeader(),
                  getParentForChildren(),
                  isClean());
          rpcHeader_ = null;
        }
        return rpcHeaderBuilder_;
      }

      private long projectId_ ;
      /**
       * <code>int64 projectId = 2;</code>
       */
      public long getProjectId() {
        return projectId_;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder setProjectId(long value) {
        
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetProductInventory180AgeRequest)
    }

    // @@protoc_insertion_point(class_scope:GetProductInventory180AgeRequest)
    private static final com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest();
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProductInventory180AgeRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetProductInventory180AgeRequest>() {
      public GetProductInventory180AgeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetProductInventory180AgeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetProductInventory180AgeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProductInventory180AgeRequest> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetProductInventory180AgeResponOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetProductInventory180AgeRespon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> 
        getListList();
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getList(int index);
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    java.util.List<? extends com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetProductInventory180AgeRespon}
   */
  public  static final class GetProductInventory180AgeRespon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetProductInventory180AgeRespon)
      GetProductInventory180AgeResponOrBuilder {
    // Use GetProductInventory180AgeRespon.newBuilder() to construct.
    private GetProductInventory180AgeRespon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProductInventory180AgeRespon() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetProductInventory180AgeRespon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRespon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRespon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> list_;
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    public java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> getListList() {
      return list_;
    }
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    public java.util.List<? extends com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .ProductInventory180Age list = 1;</code>
     */
    public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon other = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetProductInventory180AgeRespon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetProductInventory180AgeRespon)
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeResponOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRespon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRespon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_GetProductInventory180AgeRespon_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon build() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon buildPartial() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon result = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon other) {
        if (other == com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder> listBuilder_;

      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder setList(
          int index, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder setList(
          int index, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder addList(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder addList(
          int index, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder addList(
          com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder addList(
          int index, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public java.util.List<? extends com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductInventory180Age list = 1;</code>
       */
      public java.util.List<com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetProductInventory180AgeRespon)
    }

    // @@protoc_insertion_point(class_scope:GetProductInventory180AgeRespon)
    private static final com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon();
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProductInventory180AgeRespon>
        PARSER = new com.google.protobuf.AbstractParser<GetProductInventory180AgeRespon>() {
      public GetProductInventory180AgeRespon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetProductInventory180AgeRespon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetProductInventory180AgeRespon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProductInventory180AgeRespon> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.GetProductInventory180AgeRespon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductInventory180AgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductInventory180Age)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *商品型号
     * </pre>
     *
     * <code>string productCode = 1;</code>
     */
    java.lang.String getProductCode();
    /**
     * <pre>
     *商品型号
     * </pre>
     *
     * <code>string productCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductCodeBytes();

    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>double sumOfmoney = 2;</code>
     */
    double getSumOfmoney();

    /**
     * <pre>
     *金额占比
     * </pre>
     *
     * <code>double proportion = 3;</code>
     */
    double getProportion();
  }
  /**
   * Protobuf type {@code ProductInventory180Age}
   */
  public  static final class ProductInventory180Age extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductInventory180Age)
      ProductInventory180AgeOrBuilder {
    // Use ProductInventory180Age.newBuilder() to construct.
    private ProductInventory180Age(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductInventory180Age() {
      productCode_ = "";
      sumOfmoney_ = 0D;
      proportion_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProductInventory180Age(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              productCode_ = s;
              break;
            }
            case 17: {

              sumOfmoney_ = input.readDouble();
              break;
            }
            case 25: {

              proportion_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_ProductInventory180Age_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_ProductInventory180Age_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder.class);
    }

    public static final int PRODUCTCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object productCode_;
    /**
     * <pre>
     *商品型号
     * </pre>
     *
     * <code>string productCode = 1;</code>
     */
    public java.lang.String getProductCode() {
      java.lang.Object ref = productCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *商品型号
     * </pre>
     *
     * <code>string productCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductCodeBytes() {
      java.lang.Object ref = productCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUMOFMONEY_FIELD_NUMBER = 2;
    private double sumOfmoney_;
    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>double sumOfmoney = 2;</code>
     */
    public double getSumOfmoney() {
      return sumOfmoney_;
    }

    public static final int PROPORTION_FIELD_NUMBER = 3;
    private double proportion_;
    /**
     * <pre>
     *金额占比
     * </pre>
     *
     * <code>double proportion = 3;</code>
     */
    public double getProportion() {
      return proportion_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProductCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productCode_);
      }
      if (sumOfmoney_ != 0D) {
        output.writeDouble(2, sumOfmoney_);
      }
      if (proportion_ != 0D) {
        output.writeDouble(3, proportion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProductCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productCode_);
      }
      if (sumOfmoney_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sumOfmoney_);
      }
      if (proportion_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, proportion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age other = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age) obj;

      boolean result = true;
      result = result && getProductCode()
          .equals(other.getProductCode());
      result = result && (
          java.lang.Double.doubleToLongBits(getSumOfmoney())
          == java.lang.Double.doubleToLongBits(
              other.getSumOfmoney()));
      result = result && (
          java.lang.Double.doubleToLongBits(getProportion())
          == java.lang.Double.doubleToLongBits(
              other.getProportion()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getProductCode().hashCode();
      hash = (37 * hash) + SUMOFMONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSumOfmoney()));
      hash = (37 * hash) + PROPORTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProportion()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductInventory180Age}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductInventory180Age)
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180AgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_ProductInventory180Age_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_ProductInventory180Age_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.class, com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        productCode_ = "";

        sumOfmoney_ = 0D;

        proportion_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.internal_static_ProductInventory180Age_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age build() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age buildPartial() {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age result = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age(this);
        result.productCode_ = productCode_;
        result.sumOfmoney_ = sumOfmoney_;
        result.proportion_ = proportion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age other) {
        if (other == com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age.getDefaultInstance()) return this;
        if (!other.getProductCode().isEmpty()) {
          productCode_ = other.productCode_;
          onChanged();
        }
        if (other.getSumOfmoney() != 0D) {
          setSumOfmoney(other.getSumOfmoney());
        }
        if (other.getProportion() != 0D) {
          setProportion(other.getProportion());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object productCode_ = "";
      /**
       * <pre>
       *商品型号
       * </pre>
       *
       * <code>string productCode = 1;</code>
       */
      public java.lang.String getProductCode() {
        java.lang.Object ref = productCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *商品型号
       * </pre>
       *
       * <code>string productCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductCodeBytes() {
        java.lang.Object ref = productCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *商品型号
       * </pre>
       *
       * <code>string productCode = 1;</code>
       */
      public Builder setProductCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *商品型号
       * </pre>
       *
       * <code>string productCode = 1;</code>
       */
      public Builder clearProductCode() {
        
        productCode_ = getDefaultInstance().getProductCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *商品型号
       * </pre>
       *
       * <code>string productCode = 1;</code>
       */
      public Builder setProductCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productCode_ = value;
        onChanged();
        return this;
      }

      private double sumOfmoney_ ;
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double sumOfmoney = 2;</code>
       */
      public double getSumOfmoney() {
        return sumOfmoney_;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double sumOfmoney = 2;</code>
       */
      public Builder setSumOfmoney(double value) {
        
        sumOfmoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double sumOfmoney = 2;</code>
       */
      public Builder clearSumOfmoney() {
        
        sumOfmoney_ = 0D;
        onChanged();
        return this;
      }

      private double proportion_ ;
      /**
       * <pre>
       *金额占比
       * </pre>
       *
       * <code>double proportion = 3;</code>
       */
      public double getProportion() {
        return proportion_;
      }
      /**
       * <pre>
       *金额占比
       * </pre>
       *
       * <code>double proportion = 3;</code>
       */
      public Builder setProportion(double value) {
        
        proportion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金额占比
       * </pre>
       *
       * <code>double proportion = 3;</code>
       */
      public Builder clearProportion() {
        
        proportion_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProductInventory180Age)
    }

    // @@protoc_insertion_point(class_scope:ProductInventory180Age)
    private static final com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age();
    }

    public static com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductInventory180Age>
        PARSER = new com.google.protobuf.AbstractParser<ProductInventory180Age>() {
      public ProductInventory180Age parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProductInventory180Age(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductInventory180Age> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductInventory180Age> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.productinventory180age.microservice.ProductInventory180AgeStructure.ProductInventory180Age getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProductInventory180AgeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProductInventory180AgeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProductInventory180AgeRespon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProductInventory180AgeRespon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductInventory180Age_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductInventory180Age_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034productinventory180age.proto\032\037gongxiao" +
      ".global.structure.proto\"T\n GetProductInv" +
      "entory180AgeRequest\022\035\n\trpcHeader\030\001 \001(\0132\n" +
      ".RpcHeader\022\021\n\tprojectId\030\002 \001(\003\"H\n\037GetProd" +
      "uctInventory180AgeRespon\022%\n\004list\030\001 \003(\0132\027" +
      ".ProductInventory180Age\"U\n\026ProductInvent" +
      "ory180Age\022\023\n\013productCode\030\001 \001(\t\022\022\n\nsumOfm" +
      "oney\030\002 \001(\001\022\022\n\nproportion\030\003 \001(\0012~\n\035Produc" +
      "tInventory180AgeService\022]\n\024getWholeInven" +
      "toryAge\022!.GetProductInventory180AgeReque",
      "st\032 .GetProductInventory180AgeRespon\"\000Bf" +
      "\nCcom.yhglobal.gongxiao.inventory.produc" +
      "tinventory180age.microserviceB\037ProductIn" +
      "ventory180AgeStructureb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor(),
        }, assigner);
    internal_static_GetProductInventory180AgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetProductInventory180AgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProductInventory180AgeRequest_descriptor,
        new java.lang.String[] { "RpcHeader", "ProjectId", });
    internal_static_GetProductInventory180AgeRespon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetProductInventory180AgeRespon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProductInventory180AgeRespon_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ProductInventory180Age_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductInventory180Age_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductInventory180Age_descriptor,
        new java.lang.String[] { "ProductCode", "SumOfmoney", "Proportion", });
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
