// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PurchaseFile.proto

package com.yhglobal.gongxiao.purchase.microservice;

public final class PurchaseFileStructure {
  private PurchaseFileStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PurchaseFileReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PurchaseFileReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    boolean hasRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder();

    /**
     * <code>string filePath = 2;</code>
     */
    java.lang.String getFilePath();
    /**
     * <code>string filePath = 2;</code>
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <code>string projectId = 3;</code>
     */
    java.lang.String getProjectId();
    /**
     * <code>string projectId = 3;</code>
     */
    com.google.protobuf.ByteString
        getProjectIdBytes();

    /**
     * <code>string projectName = 4;</code>
     */
    java.lang.String getProjectName();
    /**
     * <code>string projectName = 4;</code>
     */
    com.google.protobuf.ByteString
        getProjectNameBytes();
  }
  /**
   * Protobuf type {@code PurchaseFileReq}
   */
  public  static final class PurchaseFileReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PurchaseFileReq)
      PurchaseFileReqOrBuilder {
    // Use PurchaseFileReq.newBuilder() to construct.
    private PurchaseFileReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PurchaseFileReq() {
      filePath_ = "";
      projectId_ = "";
      projectName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PurchaseFileReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder subBuilder = null;
              if (rpcHeader_ != null) {
                subBuilder = rpcHeader_.toBuilder();
              }
              rpcHeader_ = input.readMessage(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcHeader_);
                rpcHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              projectId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              projectName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.Builder.class);
    }

    public static final int RPCHEADER_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_;
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public boolean hasRpcHeader() {
      return rpcHeader_ != null;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
      return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
      return getRpcHeader();
    }

    public static final int FILEPATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object filePath_;
    /**
     * <code>string filePath = 2;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <code>string filePath = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object projectId_;
    /**
     * <code>string projectId = 3;</code>
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      }
    }
    /**
     * <code>string projectId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object projectName_;
    /**
     * <code>string projectName = 4;</code>
     */
    public java.lang.String getProjectName() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      }
    }
    /**
     * <code>string projectName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcHeader_ != null) {
        output.writeMessage(1, getRpcHeader());
      }
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filePath_);
      }
      if (!getProjectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, projectId_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, projectName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRpcHeader());
      }
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filePath_);
      }
      if (!getProjectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, projectId_);
      }
      if (!getProjectNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, projectName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq other = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq) obj;

      boolean result = true;
      result = result && (hasRpcHeader() == other.hasRpcHeader());
      if (hasRpcHeader()) {
        result = result && getRpcHeader()
            .equals(other.getRpcHeader());
      }
      result = result && getFilePath()
          .equals(other.getFilePath());
      result = result && getProjectId()
          .equals(other.getProjectId());
      result = result && getProjectName()
          .equals(other.getProjectName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRpcHeader()) {
        hash = (37 * hash) + RPCHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getRpcHeader().hashCode();
      }
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
      hash = (53 * hash) + getProjectId().hashCode();
      hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProjectName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PurchaseFileReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PurchaseFileReq)
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }
        filePath_ = "";

        projectId_ = "";

        projectName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileReq_descriptor;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq build() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq buildPartial() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq result = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq(this);
        if (rpcHeaderBuilder_ == null) {
          result.rpcHeader_ = rpcHeader_;
        } else {
          result.rpcHeader_ = rpcHeaderBuilder_.build();
        }
        result.filePath_ = filePath_;
        result.projectId_ = projectId_;
        result.projectName_ = projectName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq) {
          return mergeFrom((com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq other) {
        if (other == com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq.getDefaultInstance()) return this;
        if (other.hasRpcHeader()) {
          mergeRpcHeader(other.getRpcHeader());
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (!other.getProjectId().isEmpty()) {
          projectId_ = other.projectId_;
          onChanged();
        }
        if (!other.getProjectName().isEmpty()) {
          projectName_ = other.projectName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> rpcHeaderBuilder_;
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public boolean hasRpcHeader() {
        return rpcHeaderBuilder_ != null || rpcHeader_ != null;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        } else {
          return rpcHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcHeader_ = value;
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder builderForValue) {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = builderForValue.build();
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder mergeRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (rpcHeader_ != null) {
            rpcHeader_ =
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.newBuilder(rpcHeader_).mergeFrom(value).buildPartial();
          } else {
            rpcHeader_ = value;
          }
          onChanged();
        } else {
          rpcHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder clearRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
          onChanged();
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder getRpcHeaderBuilder() {
        
        onChanged();
        return getRpcHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
        if (rpcHeaderBuilder_ != null) {
          return rpcHeaderBuilder_.getMessageOrBuilder();
        } else {
          return rpcHeader_ == null ?
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> 
          getRpcHeaderFieldBuilder() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder>(
                  getRpcHeader(),
                  getParentForChildren(),
                  isClean());
          rpcHeader_ = null;
        }
        return rpcHeaderBuilder_;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <code>string filePath = 2;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string filePath = 2;</code>
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object projectId_ = "";
      /**
       * <code>string projectId = 3;</code>
       */
      public java.lang.String getProjectId() {
        java.lang.Object ref = projectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          projectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string projectId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProjectIdBytes() {
        java.lang.Object ref = projectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string projectId = 3;</code>
       */
      public Builder setProjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string projectId = 3;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = getDefaultInstance().getProjectId();
        onChanged();
        return this;
      }
      /**
       * <code>string projectId = 3;</code>
       */
      public Builder setProjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object projectName_ = "";
      /**
       * <code>string projectName = 4;</code>
       */
      public java.lang.String getProjectName() {
        java.lang.Object ref = projectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          projectName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string projectName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProjectNameBytes() {
        java.lang.Object ref = projectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string projectName = 4;</code>
       */
      public Builder setProjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 4;</code>
       */
      public Builder clearProjectName() {
        
        projectName_ = getDefaultInstance().getProjectName();
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 4;</code>
       */
      public Builder setProjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PurchaseFileReq)
    }

    // @@protoc_insertion_point(class_scope:PurchaseFileReq)
    private static final com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq();
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PurchaseFileReq>
        PARSER = new com.google.protobuf.AbstractParser<PurchaseFileReq>() {
      public PurchaseFileReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PurchaseFileReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PurchaseFileReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PurchaseFileReq> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PurchaseFileRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PurchaseFileResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    boolean hasRpcResultPurchaseFile();
    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getRpcResultPurchaseFile();
    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder getRpcResultPurchaseFileOrBuilder();
  }
  /**
   * Protobuf type {@code PurchaseFileResp}
   */
  public  static final class PurchaseFileResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PurchaseFileResp)
      PurchaseFileRespOrBuilder {
    // Use PurchaseFileResp.newBuilder() to construct.
    private PurchaseFileResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PurchaseFileResp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PurchaseFileResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder subBuilder = null;
              if (rpcResultPurchaseFile_ != null) {
                subBuilder = rpcResultPurchaseFile_.toBuilder();
              }
              rpcResultPurchaseFile_ = input.readMessage(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcResultPurchaseFile_);
                rpcResultPurchaseFile_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.Builder.class);
    }

    public static final int RPCRESULTPURCHASEFILE_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile rpcResultPurchaseFile_;
    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    public boolean hasRpcResultPurchaseFile() {
      return rpcResultPurchaseFile_ != null;
    }
    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getRpcResultPurchaseFile() {
      return rpcResultPurchaseFile_ == null ? com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.getDefaultInstance() : rpcResultPurchaseFile_;
    }
    /**
     * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
     */
    public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder getRpcResultPurchaseFileOrBuilder() {
      return getRpcResultPurchaseFile();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcResultPurchaseFile_ != null) {
        output.writeMessage(1, getRpcResultPurchaseFile());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcResultPurchaseFile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRpcResultPurchaseFile());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp other = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp) obj;

      boolean result = true;
      result = result && (hasRpcResultPurchaseFile() == other.hasRpcResultPurchaseFile());
      if (hasRpcResultPurchaseFile()) {
        result = result && getRpcResultPurchaseFile()
            .equals(other.getRpcResultPurchaseFile());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRpcResultPurchaseFile()) {
        hash = (37 * hash) + RPCRESULTPURCHASEFILE_FIELD_NUMBER;
        hash = (53 * hash) + getRpcResultPurchaseFile().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PurchaseFileResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PurchaseFileResp)
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rpcResultPurchaseFileBuilder_ == null) {
          rpcResultPurchaseFile_ = null;
        } else {
          rpcResultPurchaseFile_ = null;
          rpcResultPurchaseFileBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_PurchaseFileResp_descriptor;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp build() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp buildPartial() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp result = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp(this);
        if (rpcResultPurchaseFileBuilder_ == null) {
          result.rpcResultPurchaseFile_ = rpcResultPurchaseFile_;
        } else {
          result.rpcResultPurchaseFile_ = rpcResultPurchaseFileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp) {
          return mergeFrom((com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp other) {
        if (other == com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp.getDefaultInstance()) return this;
        if (other.hasRpcResultPurchaseFile()) {
          mergeRpcResultPurchaseFile(other.getRpcResultPurchaseFile());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile rpcResultPurchaseFile_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder> rpcResultPurchaseFileBuilder_;
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public boolean hasRpcResultPurchaseFile() {
        return rpcResultPurchaseFileBuilder_ != null || rpcResultPurchaseFile_ != null;
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getRpcResultPurchaseFile() {
        if (rpcResultPurchaseFileBuilder_ == null) {
          return rpcResultPurchaseFile_ == null ? com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.getDefaultInstance() : rpcResultPurchaseFile_;
        } else {
          return rpcResultPurchaseFileBuilder_.getMessage();
        }
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public Builder setRpcResultPurchaseFile(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile value) {
        if (rpcResultPurchaseFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcResultPurchaseFile_ = value;
          onChanged();
        } else {
          rpcResultPurchaseFileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public Builder setRpcResultPurchaseFile(
          com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder builderForValue) {
        if (rpcResultPurchaseFileBuilder_ == null) {
          rpcResultPurchaseFile_ = builderForValue.build();
          onChanged();
        } else {
          rpcResultPurchaseFileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public Builder mergeRpcResultPurchaseFile(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile value) {
        if (rpcResultPurchaseFileBuilder_ == null) {
          if (rpcResultPurchaseFile_ != null) {
            rpcResultPurchaseFile_ =
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.newBuilder(rpcResultPurchaseFile_).mergeFrom(value).buildPartial();
          } else {
            rpcResultPurchaseFile_ = value;
          }
          onChanged();
        } else {
          rpcResultPurchaseFileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public Builder clearRpcResultPurchaseFile() {
        if (rpcResultPurchaseFileBuilder_ == null) {
          rpcResultPurchaseFile_ = null;
          onChanged();
        } else {
          rpcResultPurchaseFile_ = null;
          rpcResultPurchaseFileBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder getRpcResultPurchaseFileBuilder() {
        
        onChanged();
        return getRpcResultPurchaseFileFieldBuilder().getBuilder();
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder getRpcResultPurchaseFileOrBuilder() {
        if (rpcResultPurchaseFileBuilder_ != null) {
          return rpcResultPurchaseFileBuilder_.getMessageOrBuilder();
        } else {
          return rpcResultPurchaseFile_ == null ?
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.getDefaultInstance() : rpcResultPurchaseFile_;
        }
      }
      /**
       * <code>.RpcResultPurchaseFile rpcResultPurchaseFile = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder> 
          getRpcResultPurchaseFileFieldBuilder() {
        if (rpcResultPurchaseFileBuilder_ == null) {
          rpcResultPurchaseFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder>(
                  getRpcResultPurchaseFile(),
                  getParentForChildren(),
                  isClean());
          rpcResultPurchaseFile_ = null;
        }
        return rpcResultPurchaseFileBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PurchaseFileResp)
    }

    // @@protoc_insertion_point(class_scope:PurchaseFileResp)
    private static final com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp();
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PurchaseFileResp>
        PARSER = new com.google.protobuf.AbstractParser<PurchaseFileResp>() {
      public PurchaseFileResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PurchaseFileResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PurchaseFileResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PurchaseFileResp> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.PurchaseFileResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResultPurchaseFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcResultPurchaseFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 returnCode = 1;</code>
     */
    int getReturnCode();

    /**
     * <pre>
     *当返回错误时 对应的错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <pre>
     *当返回错误时 对应的错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code RpcResultPurchaseFile}
   */
  public  static final class RpcResultPurchaseFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcResultPurchaseFile)
      RpcResultPurchaseFileOrBuilder {
    // Use RpcResultPurchaseFile.newBuilder() to construct.
    private RpcResultPurchaseFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResultPurchaseFile() {
      returnCode_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcResultPurchaseFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              returnCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_RpcResultPurchaseFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_RpcResultPurchaseFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder.class);
    }

    public static final int RETURNCODE_FIELD_NUMBER = 1;
    private int returnCode_;
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>int32 returnCode = 1;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <pre>
     *当返回错误时 对应的错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当返回错误时 对应的错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (returnCode_ != 0) {
        output.writeInt32(1, returnCode_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (returnCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, returnCode_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile other = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile) obj;

      boolean result = true;
      result = result && (getReturnCode()
          == other.getReturnCode());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
      hash = (53 * hash) + getReturnCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcResultPurchaseFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcResultPurchaseFile)
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_RpcResultPurchaseFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_RpcResultPurchaseFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.class, com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        returnCode_ = 0;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.internal_static_RpcResultPurchaseFile_descriptor;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile build() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile buildPartial() {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile result = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile(this);
        result.returnCode_ = returnCode_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile) {
          return mergeFrom((com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile other) {
        if (other == com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile.getDefaultInstance()) return this;
        if (other.getReturnCode() != 0) {
          setReturnCode(other.getReturnCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int returnCode_ ;
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public int getReturnCode() {
        return returnCode_;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public Builder setReturnCode(int value) {
        
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>int32 returnCode = 1;</code>
       */
      public Builder clearReturnCode() {
        
        returnCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       *当返回错误时 对应的错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当返回错误时 对应的错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当返回错误时 对应的错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当返回错误时 对应的错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当返回错误时 对应的错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RpcResultPurchaseFile)
    }

    // @@protoc_insertion_point(class_scope:RpcResultPurchaseFile)
    private static final com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile();
    }

    public static com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResultPurchaseFile>
        PARSER = new com.google.protobuf.AbstractParser<RpcResultPurchaseFile>() {
      public RpcResultPurchaseFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcResultPurchaseFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcResultPurchaseFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResultPurchaseFile> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.purchase.microservice.PurchaseFileStructure.RpcResultPurchaseFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PurchaseFileReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PurchaseFileReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PurchaseFileResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PurchaseFileResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcResultPurchaseFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcResultPurchaseFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PurchaseFile.proto\032\037gongxiao.global.st" +
      "ructure.proto\"j\n\017PurchaseFileReq\022\035\n\trpcH" +
      "eader\030\001 \001(\0132\n.RpcHeader\022\020\n\010filePath\030\002 \001(" +
      "\t\022\021\n\tprojectId\030\003 \001(\t\022\023\n\013projectName\030\004 \001(" +
      "\t\"I\n\020PurchaseFileResp\0225\n\025rpcResultPurcha" +
      "seFile\030\001 \001(\0132\026.RpcResultPurchaseFile\"8\n\025" +
      "RpcResultPurchaseFile\022\022\n\nreturnCode\030\001 \001(" +
      "\005\022\013\n\003msg\030\002 \001(\t2V\n\023PurchaseFileService\022?\n" +
      "\026parsePurchaseOrderList\022\020.PurchaseFileRe" +
      "q\032\021.PurchaseFileResp\"\000BD\n+com.yhglobal.g",
      "ongxiao.purchase.microserviceB\025PurchaseF" +
      "ileStructureb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor(),
        }, assigner);
    internal_static_PurchaseFileReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PurchaseFileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PurchaseFileReq_descriptor,
        new java.lang.String[] { "RpcHeader", "FilePath", "ProjectId", "ProjectName", });
    internal_static_PurchaseFileResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PurchaseFileResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PurchaseFileResp_descriptor,
        new java.lang.String[] { "RpcResultPurchaseFile", });
    internal_static_RpcResultPurchaseFile_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RpcResultPurchaseFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcResultPurchaseFile_descriptor,
        new java.lang.String[] { "ReturnCode", "Msg", });
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
