// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protomodel.proto

package com.yhglobal.gongxiao.grpc.model.proto;

public final class ProtoModelStructure {
  private ProtoModelStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *字符串
     * </pre>
     *
     * <code>string traceId = 1;</code>
     */
    String getTraceId();
    /**
     * <pre>
     *字符串
     * </pre>
     *
     * <code>string traceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <pre>
     *整形
     * </pre>
     *
     * <code>int32 projectId = 2;</code>
     */
    int getProjectId();

    /**
     * <pre>
     *布尔
     * </pre>
     *
     * <code>bool isDeleted = 3;</code>
     */
    boolean getIsDeleted();

    /**
     * <pre>
     *byte[]
     * </pre>
     *
     * <code>bytes body = 4;</code>
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    java.util.List<ProtoInnerModel>
        getInnerModelList();
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    ProtoInnerModel getInnerModel(int index);
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    int getInnerModelCount();
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    java.util.List<? extends ProtoInnerModelOrBuilder>
        getInnerModelOrBuilderList();
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    ProtoInnerModelOrBuilder getInnerModelOrBuilder(
            int index);

    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */
    int getMappingCount();
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */
    boolean containsMapping(
            String key);
    /**
     * Use {@link #getMappingMap()} instead.
     */
    @Deprecated
    java.util.Map<String, ProtoInnerModel>
    getMapping();
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */
    java.util.Map<String, ProtoInnerModel>
    getMappingMap();
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    ProtoInnerModel getMappingOrDefault(
            String key,
            ProtoInnerModel defaultValue);
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    ProtoInnerModel getMappingOrThrow(
            String key);
  }
  /**
   * <pre>
   *rpc调用时 约定传递的header信息
   * </pre>
   *
   * Protobuf type {@code ProtoModel}
   */
  public  static final class ProtoModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoModel)
      ProtoModelOrBuilder {
    // Use ProtoModel.newBuilder() to construct.
    private ProtoModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoModel() {
      traceId_ = "";
      projectId_ = 0;
      isDeleted_ = false;
      body_ = com.google.protobuf.ByteString.EMPTY;
      innerModel_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              traceId_ = s;
              break;
            }
            case 16: {

              projectId_ = input.readInt32();
              break;
            }
            case 24: {

              isDeleted_ = input.readBool();
              break;
            }
            case 34: {

              body_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                innerModel_ = new java.util.ArrayList<ProtoInnerModel>();
                mutable_bitField0_ |= 0x00000010;
              }
              innerModel_.add(
                  input.readMessage(ProtoInnerModel.parser(), extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                mapping_ = com.google.protobuf.MapField.newMapField(
                    MappingDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<String, ProtoInnerModel>
              mapping__ = input.readMessage(
                  MappingDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mapping_.getMutableMap().put(
                  mapping__.getKey(), mapping__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          innerModel_ = java.util.Collections.unmodifiableList(innerModel_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoModelStructure.internal_static_ProtoModel_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMapping();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoModelStructure.internal_static_ProtoModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoModel.class, Builder.class);
    }

    private int bitField0_;
    public static final int TRACEID_FIELD_NUMBER = 1;
    private volatile Object traceId_;
    /**
     * <pre>
     *字符串
     * </pre>
     *
     * <code>string traceId = 1;</code>
     */
    public String getTraceId() {
      Object ref = traceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *字符串
     * </pre>
     *
     * <code>string traceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTID_FIELD_NUMBER = 2;
    private int projectId_;
    /**
     * <pre>
     *整形
     * </pre>
     *
     * <code>int32 projectId = 2;</code>
     */
    public int getProjectId() {
      return projectId_;
    }

    public static final int ISDELETED_FIELD_NUMBER = 3;
    private boolean isDeleted_;
    /**
     * <pre>
     *布尔
     * </pre>
     *
     * <code>bool isDeleted = 3;</code>
     */
    public boolean getIsDeleted() {
      return isDeleted_;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     *byte[]
     * </pre>
     *
     * <code>bytes body = 4;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int INNERMODEL_FIELD_NUMBER = 5;
    private java.util.List<ProtoInnerModel> innerModel_;
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    public java.util.List<ProtoInnerModel> getInnerModelList() {
      return innerModel_;
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    public java.util.List<? extends ProtoInnerModelOrBuilder>
        getInnerModelOrBuilderList() {
      return innerModel_;
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    public int getInnerModelCount() {
      return innerModel_.size();
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    public ProtoInnerModel getInnerModel(int index) {
      return innerModel_.get(index);
    }
    /**
     * <pre>
     *list
     * </pre>
     *
     * <code>repeated .ProtoInnerModel innerModel = 5;</code>
     */
    public ProtoInnerModelOrBuilder getInnerModelOrBuilder(
        int index) {
      return innerModel_.get(index);
    }

    public static final int MAPPING_FIELD_NUMBER = 6;
    private static final class MappingDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, ProtoInnerModel> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, ProtoInnerModel>newDefaultInstance(
                  ProtoModelStructure.internal_static_ProtoModel_MappingEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  ProtoInnerModel.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, ProtoInnerModel> mapping_;
    private com.google.protobuf.MapField<String, ProtoInnerModel>
    internalGetMapping() {
      if (mapping_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MappingDefaultEntryHolder.defaultEntry);
      }
      return mapping_;
    }

    public int getMappingCount() {
      return internalGetMapping().getMap().size();
    }
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    public boolean containsMapping(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMapping().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMappingMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, ProtoInnerModel> getMapping() {
      return getMappingMap();
    }
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    public java.util.Map<String, ProtoInnerModel> getMappingMap() {
      return internalGetMapping().getMap();
    }
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    public ProtoInnerModel getMappingOrDefault(
        String key,
        ProtoInnerModel defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, ProtoInnerModel> map =
          internalGetMapping().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *map
     * </pre>
     *
     * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
     */

    public ProtoInnerModel getMappingOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, ProtoInnerModel> map =
          internalGetMapping().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTraceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceId_);
      }
      if (projectId_ != 0) {
        output.writeInt32(2, projectId_);
      }
      if (isDeleted_ != false) {
        output.writeBool(3, isDeleted_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(4, body_);
      }
      for (int i = 0; i < innerModel_.size(); i++) {
        output.writeMessage(5, innerModel_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMapping(),
          MappingDefaultEntryHolder.defaultEntry,
          6);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTraceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceId_);
      }
      if (projectId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, projectId_);
      }
      if (isDeleted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isDeleted_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      for (int i = 0; i < innerModel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, innerModel_.get(i));
      }
      for (java.util.Map.Entry<String, ProtoInnerModel> entry
           : internalGetMapping().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, ProtoInnerModel>
        mapping__ = MappingDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, mapping__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoModel)) {
        return super.equals(obj);
      }
      ProtoModel other = (ProtoModel) obj;

      boolean result = true;
      result = result && getTraceId()
          .equals(other.getTraceId());
      result = result && (getProjectId()
          == other.getProjectId());
      result = result && (getIsDeleted()
          == other.getIsDeleted());
      result = result && getBody()
          .equals(other.getBody());
      result = result && getInnerModelList()
          .equals(other.getInnerModelList());
      result = result && internalGetMapping().equals(
          other.internalGetMapping());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
      hash = (53 * hash) + getProjectId();
      hash = (37 * hash) + ISDELETED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDeleted());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (getInnerModelCount() > 0) {
        hash = (37 * hash) + INNERMODEL_FIELD_NUMBER;
        hash = (53 * hash) + getInnerModelList().hashCode();
      }
      if (!internalGetMapping().getMap().isEmpty()) {
        hash = (37 * hash) + MAPPING_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapping().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *rpc调用时 约定传递的header信息
     * </pre>
     *
     * Protobuf type {@code ProtoModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoModel)
        ProtoModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoModelStructure.internal_static_ProtoModel_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMapping();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableMapping();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoModelStructure.internal_static_ProtoModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoModel.class, Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.grpc.model.proto.ProtoModelStructure.ProtoModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerModelFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        traceId_ = "";

        projectId_ = 0;

        isDeleted_ = false;

        body_ = com.google.protobuf.ByteString.EMPTY;

        if (innerModelBuilder_ == null) {
          innerModel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          innerModelBuilder_.clear();
        }
        internalGetMutableMapping().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoModelStructure.internal_static_ProtoModel_descriptor;
      }

      public ProtoModel getDefaultInstanceForType() {
        return ProtoModel.getDefaultInstance();
      }

      public ProtoModel build() {
        ProtoModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoModel buildPartial() {
        ProtoModel result = new ProtoModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.traceId_ = traceId_;
        result.projectId_ = projectId_;
        result.isDeleted_ = isDeleted_;
        result.body_ = body_;
        if (innerModelBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            innerModel_ = java.util.Collections.unmodifiableList(innerModel_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.innerModel_ = innerModel_;
        } else {
          result.innerModel_ = innerModelBuilder_.build();
        }
        result.mapping_ = internalGetMapping();
        result.mapping_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoModel) {
          return mergeFrom((ProtoModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoModel other) {
        if (other == ProtoModel.getDefaultInstance()) return this;
        if (!other.getTraceId().isEmpty()) {
          traceId_ = other.traceId_;
          onChanged();
        }
        if (other.getProjectId() != 0) {
          setProjectId(other.getProjectId());
        }
        if (other.getIsDeleted() != false) {
          setIsDeleted(other.getIsDeleted());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (innerModelBuilder_ == null) {
          if (!other.innerModel_.isEmpty()) {
            if (innerModel_.isEmpty()) {
              innerModel_ = other.innerModel_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureInnerModelIsMutable();
              innerModel_.addAll(other.innerModel_);
            }
            onChanged();
          }
        } else {
          if (!other.innerModel_.isEmpty()) {
            if (innerModelBuilder_.isEmpty()) {
              innerModelBuilder_.dispose();
              innerModelBuilder_ = null;
              innerModel_ = other.innerModel_;
              bitField0_ = (bitField0_ & ~0x00000010);
              innerModelBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInnerModelFieldBuilder() : null;
            } else {
              innerModelBuilder_.addAllMessages(other.innerModel_);
            }
          }
        }
        internalGetMutableMapping().mergeFrom(
            other.internalGetMapping());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object traceId_ = "";
      /**
       * <pre>
       *字符串
       * </pre>
       *
       * <code>string traceId = 1;</code>
       */
      public String getTraceId() {
        Object ref = traceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          traceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *字符串
       * </pre>
       *
       * <code>string traceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *字符串
       * </pre>
       *
       * <code>string traceId = 1;</code>
       */
      public Builder setTraceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *字符串
       * </pre>
       *
       * <code>string traceId = 1;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *字符串
       * </pre>
       *
       * <code>string traceId = 1;</code>
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceId_ = value;
        onChanged();
        return this;
      }

      private int projectId_ ;
      /**
       * <pre>
       *整形
       * </pre>
       *
       * <code>int32 projectId = 2;</code>
       */
      public int getProjectId() {
        return projectId_;
      }
      /**
       * <pre>
       *整形
       * </pre>
       *
       * <code>int32 projectId = 2;</code>
       */
      public Builder setProjectId(int value) {
        
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *整形
       * </pre>
       *
       * <code>int32 projectId = 2;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = 0;
        onChanged();
        return this;
      }

      private boolean isDeleted_ ;
      /**
       * <pre>
       *布尔
       * </pre>
       *
       * <code>bool isDeleted = 3;</code>
       */
      public boolean getIsDeleted() {
        return isDeleted_;
      }
      /**
       * <pre>
       *布尔
       * </pre>
       *
       * <code>bool isDeleted = 3;</code>
       */
      public Builder setIsDeleted(boolean value) {
        
        isDeleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *布尔
       * </pre>
       *
       * <code>bool isDeleted = 3;</code>
       */
      public Builder clearIsDeleted() {
        
        isDeleted_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *byte[]
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       *byte[]
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *byte[]
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private java.util.List<ProtoInnerModel> innerModel_ =
        java.util.Collections.emptyList();
      private void ensureInnerModelIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          innerModel_ = new java.util.ArrayList<ProtoInnerModel>(innerModel_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoInnerModel, ProtoInnerModel.Builder, ProtoInnerModelOrBuilder> innerModelBuilder_;

      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public java.util.List<ProtoInnerModel> getInnerModelList() {
        if (innerModelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(innerModel_);
        } else {
          return innerModelBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public int getInnerModelCount() {
        if (innerModelBuilder_ == null) {
          return innerModel_.size();
        } else {
          return innerModelBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public ProtoInnerModel getInnerModel(int index) {
        if (innerModelBuilder_ == null) {
          return innerModel_.get(index);
        } else {
          return innerModelBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder setInnerModel(
          int index, ProtoInnerModel value) {
        if (innerModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerModelIsMutable();
          innerModel_.set(index, value);
          onChanged();
        } else {
          innerModelBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder setInnerModel(
          int index, ProtoInnerModel.Builder builderForValue) {
        if (innerModelBuilder_ == null) {
          ensureInnerModelIsMutable();
          innerModel_.set(index, builderForValue.build());
          onChanged();
        } else {
          innerModelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder addInnerModel(ProtoInnerModel value) {
        if (innerModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerModelIsMutable();
          innerModel_.add(value);
          onChanged();
        } else {
          innerModelBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder addInnerModel(
          int index, ProtoInnerModel value) {
        if (innerModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerModelIsMutable();
          innerModel_.add(index, value);
          onChanged();
        } else {
          innerModelBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder addInnerModel(
          ProtoInnerModel.Builder builderForValue) {
        if (innerModelBuilder_ == null) {
          ensureInnerModelIsMutable();
          innerModel_.add(builderForValue.build());
          onChanged();
        } else {
          innerModelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder addInnerModel(
          int index, ProtoInnerModel.Builder builderForValue) {
        if (innerModelBuilder_ == null) {
          ensureInnerModelIsMutable();
          innerModel_.add(index, builderForValue.build());
          onChanged();
        } else {
          innerModelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder addAllInnerModel(
          Iterable<? extends ProtoInnerModel> values) {
        if (innerModelBuilder_ == null) {
          ensureInnerModelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, innerModel_);
          onChanged();
        } else {
          innerModelBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder clearInnerModel() {
        if (innerModelBuilder_ == null) {
          innerModel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          innerModelBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public Builder removeInnerModel(int index) {
        if (innerModelBuilder_ == null) {
          ensureInnerModelIsMutable();
          innerModel_.remove(index);
          onChanged();
        } else {
          innerModelBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public ProtoInnerModel.Builder getInnerModelBuilder(
          int index) {
        return getInnerModelFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public ProtoInnerModelOrBuilder getInnerModelOrBuilder(
          int index) {
        if (innerModelBuilder_ == null) {
          return innerModel_.get(index);  } else {
          return innerModelBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public java.util.List<? extends ProtoInnerModelOrBuilder>
           getInnerModelOrBuilderList() {
        if (innerModelBuilder_ != null) {
          return innerModelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(innerModel_);
        }
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public ProtoInnerModel.Builder addInnerModelBuilder() {
        return getInnerModelFieldBuilder().addBuilder(
            ProtoInnerModel.getDefaultInstance());
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public ProtoInnerModel.Builder addInnerModelBuilder(
          int index) {
        return getInnerModelFieldBuilder().addBuilder(
            index, ProtoInnerModel.getDefaultInstance());
      }
      /**
       * <pre>
       *list
       * </pre>
       *
       * <code>repeated .ProtoInnerModel innerModel = 5;</code>
       */
      public java.util.List<ProtoInnerModel.Builder>
           getInnerModelBuilderList() {
        return getInnerModelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoInnerModel, ProtoInnerModel.Builder, ProtoInnerModelOrBuilder>
          getInnerModelFieldBuilder() {
        if (innerModelBuilder_ == null) {
          innerModelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoInnerModel, ProtoInnerModel.Builder, ProtoInnerModelOrBuilder>(
                  innerModel_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          innerModel_ = null;
        }
        return innerModelBuilder_;
      }

      private com.google.protobuf.MapField<
          String, ProtoInnerModel> mapping_;
      private com.google.protobuf.MapField<String, ProtoInnerModel>
      internalGetMapping() {
        if (mapping_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MappingDefaultEntryHolder.defaultEntry);
        }
        return mapping_;
      }
      private com.google.protobuf.MapField<String, ProtoInnerModel>
      internalGetMutableMapping() {
        onChanged();;
        if (mapping_ == null) {
          mapping_ = com.google.protobuf.MapField.newMapField(
              MappingDefaultEntryHolder.defaultEntry);
        }
        if (!mapping_.isMutable()) {
          mapping_ = mapping_.copy();
        }
        return mapping_;
      }

      public int getMappingCount() {
        return internalGetMapping().getMap().size();
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public boolean containsMapping(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMapping().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMappingMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, ProtoInnerModel> getMapping() {
        return getMappingMap();
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public java.util.Map<String, ProtoInnerModel> getMappingMap() {
        return internalGetMapping().getMap();
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public ProtoInnerModel getMappingOrDefault(
          String key,
          ProtoInnerModel defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, ProtoInnerModel> map =
            internalGetMapping().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public ProtoInnerModel getMappingOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, ProtoInnerModel> map =
            internalGetMapping().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMapping() {
        internalGetMutableMapping().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public Builder removeMapping(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMapping().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, ProtoInnerModel>
      getMutableMapping() {
        return internalGetMutableMapping().getMutableMap();
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */
      public Builder putMapping(
          String key,
          ProtoInnerModel value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableMapping().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *map
       * </pre>
       *
       * <code>map&lt;string, .ProtoInnerModel&gt; mapping = 6;</code>
       */

      public Builder putAllMapping(
          java.util.Map<String, ProtoInnerModel> values) {
        internalGetMutableMapping().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtoModel)
    }

    // @@protoc_insertion_point(class_scope:ProtoModel)
    private static final ProtoModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoModel();
    }

    public static ProtoModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoModel>
        PARSER = new com.google.protobuf.AbstractParser<ProtoModel>() {
      public ProtoModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoModel> getParserForType() {
      return PARSER;
    }

    public ProtoModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoInnerModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoInnerModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string innerId = 1;</code>
     */
    String getInnerId();
    /**
     * <code>string innerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getInnerIdBytes();
  }
  /**
   * Protobuf type {@code ProtoInnerModel}
   */
  public  static final class ProtoInnerModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoInnerModel)
      ProtoInnerModelOrBuilder {
    // Use ProtoInnerModel.newBuilder() to construct.
    private ProtoInnerModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoInnerModel() {
      innerId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoInnerModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              innerId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoModelStructure.internal_static_ProtoInnerModel_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoModelStructure.internal_static_ProtoInnerModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoInnerModel.class, Builder.class);
    }

    public static final int INNERID_FIELD_NUMBER = 1;
    private volatile Object innerId_;
    /**
     * <code>string innerId = 1;</code>
     */
    public String getInnerId() {
      Object ref = innerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        innerId_ = s;
        return s;
      }
    }
    /**
     * <code>string innerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInnerIdBytes() {
      Object ref = innerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        innerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInnerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, innerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInnerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, innerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoInnerModel)) {
        return super.equals(obj);
      }
      ProtoInnerModel other = (ProtoInnerModel) obj;

      boolean result = true;
      result = result && getInnerId()
          .equals(other.getInnerId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INNERID_FIELD_NUMBER;
      hash = (53 * hash) + getInnerId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoInnerModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoInnerModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoInnerModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoInnerModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoInnerModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoInnerModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoInnerModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoInnerModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoInnerModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoInnerModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoInnerModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoInnerModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoInnerModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoInnerModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoInnerModel)
        ProtoInnerModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoModelStructure.internal_static_ProtoInnerModel_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoModelStructure.internal_static_ProtoInnerModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoInnerModel.class, Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.grpc.model.proto.ProtoModelStructure.ProtoInnerModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        innerId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoModelStructure.internal_static_ProtoInnerModel_descriptor;
      }

      public ProtoInnerModel getDefaultInstanceForType() {
        return ProtoInnerModel.getDefaultInstance();
      }

      public ProtoInnerModel build() {
        ProtoInnerModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoInnerModel buildPartial() {
        ProtoInnerModel result = new ProtoInnerModel(this);
        result.innerId_ = innerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoInnerModel) {
          return mergeFrom((ProtoInnerModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoInnerModel other) {
        if (other == ProtoInnerModel.getDefaultInstance()) return this;
        if (!other.getInnerId().isEmpty()) {
          innerId_ = other.innerId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoInnerModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoInnerModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object innerId_ = "";
      /**
       * <code>string innerId = 1;</code>
       */
      public String getInnerId() {
        Object ref = innerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          innerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string innerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInnerIdBytes() {
        Object ref = innerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          innerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string innerId = 1;</code>
       */
      public Builder setInnerId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        innerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string innerId = 1;</code>
       */
      public Builder clearInnerId() {
        
        innerId_ = getDefaultInstance().getInnerId();
        onChanged();
        return this;
      }
      /**
       * <code>string innerId = 1;</code>
       */
      public Builder setInnerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        innerId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtoInnerModel)
    }

    // @@protoc_insertion_point(class_scope:ProtoInnerModel)
    private static final ProtoInnerModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoInnerModel();
    }

    public static ProtoInnerModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoInnerModel>
        PARSER = new com.google.protobuf.AbstractParser<ProtoInnerModel>() {
      public ProtoInnerModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoInnerModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoInnerModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoInnerModel> getParserForType() {
      return PARSER;
    }

    public ProtoInnerModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoModel_MappingEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoModel_MappingEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoInnerModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoInnerModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020protomodel.proto\"\344\001\n\nProtoModel\022\017\n\007tra" +
      "ceId\030\001 \001(\t\022\021\n\tprojectId\030\002 \001(\005\022\021\n\tisDelet" +
      "ed\030\003 \001(\010\022\014\n\004body\030\004 \001(\014\022$\n\ninnerModel\030\005 \003" +
      "(\0132\020.ProtoInnerModel\022)\n\007mapping\030\006 \003(\0132\030." +
      "ProtoModel.MappingEntry\032@\n\014MappingEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001(\0132\020.ProtoInner" +
      "Model:\0028\001\"\"\n\017ProtoInnerModel\022\017\n\007innerId\030" +
      "\001 \001(\tB=\n&com.yhglobal.gongxiao.grpc.mode" +
      "l.protoB\023ProtoModelStructureb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtoModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoModel_descriptor,
        new String[] { "TraceId", "ProjectId", "IsDeleted", "Body", "InnerModel", "Mapping", });
    internal_static_ProtoModel_MappingEntry_descriptor =
      internal_static_ProtoModel_descriptor.getNestedTypes().get(0);
    internal_static_ProtoModel_MappingEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoModel_MappingEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ProtoInnerModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoInnerModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoInnerModel_descriptor,
        new String[] { "InnerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
