// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventorymonthamount.proto

package com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice;

public final class InventoryMonthAmountStructure {
  private InventoryMonthAmountStructure() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInventoryMonthAmountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInventoryMonthAmountRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    boolean hasRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader();
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder();

    /**
     * <code>int64 projectId = 2;</code>
     */
    long getProjectId();

    /**
     * <code>string yearMonth = 3;</code>
     */
    java.lang.String getYearMonth();
    /**
     * <code>string yearMonth = 3;</code>
     */
    com.google.protobuf.ByteString
        getYearMonthBytes();
  }
  /**
   * Protobuf type {@code GetInventoryMonthAmountRequest}
   */
  public  static final class GetInventoryMonthAmountRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInventoryMonthAmountRequest)
      GetInventoryMonthAmountRequestOrBuilder {
    // Use GetInventoryMonthAmountRequest.newBuilder() to construct.
    private GetInventoryMonthAmountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInventoryMonthAmountRequest() {
      projectId_ = 0L;
      yearMonth_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInventoryMonthAmountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder subBuilder = null;
              if (rpcHeader_ != null) {
                subBuilder = rpcHeader_.toBuilder();
              }
              rpcHeader_ = input.readMessage(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcHeader_);
                rpcHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              projectId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              yearMonth_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.Builder.class);
    }

    public static final int RPCHEADER_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_;
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public boolean hasRpcHeader() {
      return rpcHeader_ != null;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
      return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
    }
    /**
     * <code>.RpcHeader rpcHeader = 1;</code>
     */
    public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
      return getRpcHeader();
    }

    public static final int PROJECTID_FIELD_NUMBER = 2;
    private long projectId_;
    /**
     * <code>int64 projectId = 2;</code>
     */
    public long getProjectId() {
      return projectId_;
    }

    public static final int YEARMONTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object yearMonth_;
    /**
     * <code>string yearMonth = 3;</code>
     */
    public java.lang.String getYearMonth() {
      java.lang.Object ref = yearMonth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        yearMonth_ = s;
        return s;
      }
    }
    /**
     * <code>string yearMonth = 3;</code>
     */
    public com.google.protobuf.ByteString
        getYearMonthBytes() {
      java.lang.Object ref = yearMonth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        yearMonth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcHeader_ != null) {
        output.writeMessage(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        output.writeInt64(2, projectId_);
      }
      if (!getYearMonthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, yearMonth_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRpcHeader());
      }
      if (projectId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, projectId_);
      }
      if (!getYearMonthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, yearMonth_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest other = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest) obj;

      boolean result = true;
      result = result && (hasRpcHeader() == other.hasRpcHeader());
      if (hasRpcHeader()) {
        result = result && getRpcHeader()
            .equals(other.getRpcHeader());
      }
      result = result && (getProjectId()
          == other.getProjectId());
      result = result && getYearMonth()
          .equals(other.getYearMonth());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRpcHeader()) {
        hash = (37 * hash) + RPCHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getRpcHeader().hashCode();
      }
      hash = (37 * hash) + PROJECTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProjectId());
      hash = (37 * hash) + YEARMONTH_FIELD_NUMBER;
      hash = (53 * hash) + getYearMonth().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetInventoryMonthAmountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInventoryMonthAmountRequest)
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }
        projectId_ = 0L;

        yearMonth_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRequest_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest build() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest buildPartial() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest result = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest(this);
        if (rpcHeaderBuilder_ == null) {
          result.rpcHeader_ = rpcHeader_;
        } else {
          result.rpcHeader_ = rpcHeaderBuilder_.build();
        }
        result.projectId_ = projectId_;
        result.yearMonth_ = yearMonth_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest other) {
        if (other == com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest.getDefaultInstance()) return this;
        if (other.hasRpcHeader()) {
          mergeRpcHeader(other.getRpcHeader());
        }
        if (other.getProjectId() != 0L) {
          setProjectId(other.getProjectId());
        }
        if (!other.getYearMonth().isEmpty()) {
          yearMonth_ = other.yearMonth_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader rpcHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> rpcHeaderBuilder_;
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public boolean hasRpcHeader() {
        return rpcHeaderBuilder_ != null || rpcHeader_ != null;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader getRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          return rpcHeader_ == null ? com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        } else {
          return rpcHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcHeader_ = value;
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder setRpcHeader(
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder builderForValue) {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = builderForValue.build();
          onChanged();
        } else {
          rpcHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder mergeRpcHeader(com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader value) {
        if (rpcHeaderBuilder_ == null) {
          if (rpcHeader_ != null) {
            rpcHeader_ =
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.newBuilder(rpcHeader_).mergeFrom(value).buildPartial();
          } else {
            rpcHeader_ = value;
          }
          onChanged();
        } else {
          rpcHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public Builder clearRpcHeader() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeader_ = null;
          onChanged();
        } else {
          rpcHeader_ = null;
          rpcHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder getRpcHeaderBuilder() {
        
        onChanged();
        return getRpcHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      public com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder getRpcHeaderOrBuilder() {
        if (rpcHeaderBuilder_ != null) {
          return rpcHeaderBuilder_.getMessageOrBuilder();
        } else {
          return rpcHeader_ == null ?
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.getDefaultInstance() : rpcHeader_;
        }
      }
      /**
       * <code>.RpcHeader rpcHeader = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder> 
          getRpcHeaderFieldBuilder() {
        if (rpcHeaderBuilder_ == null) {
          rpcHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeader.Builder, com.yhglobal.gongxiao.microservice.GongxiaoRpc.RpcHeaderOrBuilder>(
                  getRpcHeader(),
                  getParentForChildren(),
                  isClean());
          rpcHeader_ = null;
        }
        return rpcHeaderBuilder_;
      }

      private long projectId_ ;
      /**
       * <code>int64 projectId = 2;</code>
       */
      public long getProjectId() {
        return projectId_;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder setProjectId(long value) {
        
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 projectId = 2;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object yearMonth_ = "";
      /**
       * <code>string yearMonth = 3;</code>
       */
      public java.lang.String getYearMonth() {
        java.lang.Object ref = yearMonth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          yearMonth_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string yearMonth = 3;</code>
       */
      public com.google.protobuf.ByteString
          getYearMonthBytes() {
        java.lang.Object ref = yearMonth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          yearMonth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string yearMonth = 3;</code>
       */
      public Builder setYearMonth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        yearMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string yearMonth = 3;</code>
       */
      public Builder clearYearMonth() {
        
        yearMonth_ = getDefaultInstance().getYearMonth();
        onChanged();
        return this;
      }
      /**
       * <code>string yearMonth = 3;</code>
       */
      public Builder setYearMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        yearMonth_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetInventoryMonthAmountRequest)
    }

    // @@protoc_insertion_point(class_scope:GetInventoryMonthAmountRequest)
    private static final com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest();
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInventoryMonthAmountRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetInventoryMonthAmountRequest>() {
      public GetInventoryMonthAmountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInventoryMonthAmountRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInventoryMonthAmountRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInventoryMonthAmountRequest> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetInventoryMonthAmountResponOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInventoryMonthAmountRespon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    boolean hasInventoryMonthAmount();
    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getInventoryMonthAmount();
    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder getInventoryMonthAmountOrBuilder();
  }
  /**
   * Protobuf type {@code GetInventoryMonthAmountRespon}
   */
  public  static final class GetInventoryMonthAmountRespon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInventoryMonthAmountRespon)
      GetInventoryMonthAmountResponOrBuilder {
    // Use GetInventoryMonthAmountRespon.newBuilder() to construct.
    private GetInventoryMonthAmountRespon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInventoryMonthAmountRespon() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInventoryMonthAmountRespon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder subBuilder = null;
              if (inventoryMonthAmount_ != null) {
                subBuilder = inventoryMonthAmount_.toBuilder();
              }
              inventoryMonthAmount_ = input.readMessage(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inventoryMonthAmount_);
                inventoryMonthAmount_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRespon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRespon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.Builder.class);
    }

    public static final int INVENTORYMONTHAMOUNT_FIELD_NUMBER = 1;
    private com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount inventoryMonthAmount_;
    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    public boolean hasInventoryMonthAmount() {
      return inventoryMonthAmount_ != null;
    }
    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getInventoryMonthAmount() {
      return inventoryMonthAmount_ == null ? com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.getDefaultInstance() : inventoryMonthAmount_;
    }
    /**
     * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
     */
    public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder getInventoryMonthAmountOrBuilder() {
      return getInventoryMonthAmount();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inventoryMonthAmount_ != null) {
        output.writeMessage(1, getInventoryMonthAmount());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (inventoryMonthAmount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInventoryMonthAmount());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon other = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon) obj;

      boolean result = true;
      result = result && (hasInventoryMonthAmount() == other.hasInventoryMonthAmount());
      if (hasInventoryMonthAmount()) {
        result = result && getInventoryMonthAmount()
            .equals(other.getInventoryMonthAmount());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInventoryMonthAmount()) {
        hash = (37 * hash) + INVENTORYMONTHAMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getInventoryMonthAmount().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetInventoryMonthAmountRespon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInventoryMonthAmountRespon)
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountResponOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRespon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRespon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (inventoryMonthAmountBuilder_ == null) {
          inventoryMonthAmount_ = null;
        } else {
          inventoryMonthAmount_ = null;
          inventoryMonthAmountBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_GetInventoryMonthAmountRespon_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon build() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon buildPartial() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon result = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon(this);
        if (inventoryMonthAmountBuilder_ == null) {
          result.inventoryMonthAmount_ = inventoryMonthAmount_;
        } else {
          result.inventoryMonthAmount_ = inventoryMonthAmountBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon other) {
        if (other == com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon.getDefaultInstance()) return this;
        if (other.hasInventoryMonthAmount()) {
          mergeInventoryMonthAmount(other.getInventoryMonthAmount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount inventoryMonthAmount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder> inventoryMonthAmountBuilder_;
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public boolean hasInventoryMonthAmount() {
        return inventoryMonthAmountBuilder_ != null || inventoryMonthAmount_ != null;
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getInventoryMonthAmount() {
        if (inventoryMonthAmountBuilder_ == null) {
          return inventoryMonthAmount_ == null ? com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.getDefaultInstance() : inventoryMonthAmount_;
        } else {
          return inventoryMonthAmountBuilder_.getMessage();
        }
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public Builder setInventoryMonthAmount(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount value) {
        if (inventoryMonthAmountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inventoryMonthAmount_ = value;
          onChanged();
        } else {
          inventoryMonthAmountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public Builder setInventoryMonthAmount(
          com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder builderForValue) {
        if (inventoryMonthAmountBuilder_ == null) {
          inventoryMonthAmount_ = builderForValue.build();
          onChanged();
        } else {
          inventoryMonthAmountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public Builder mergeInventoryMonthAmount(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount value) {
        if (inventoryMonthAmountBuilder_ == null) {
          if (inventoryMonthAmount_ != null) {
            inventoryMonthAmount_ =
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.newBuilder(inventoryMonthAmount_).mergeFrom(value).buildPartial();
          } else {
            inventoryMonthAmount_ = value;
          }
          onChanged();
        } else {
          inventoryMonthAmountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public Builder clearInventoryMonthAmount() {
        if (inventoryMonthAmountBuilder_ == null) {
          inventoryMonthAmount_ = null;
          onChanged();
        } else {
          inventoryMonthAmount_ = null;
          inventoryMonthAmountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder getInventoryMonthAmountBuilder() {
        
        onChanged();
        return getInventoryMonthAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder getInventoryMonthAmountOrBuilder() {
        if (inventoryMonthAmountBuilder_ != null) {
          return inventoryMonthAmountBuilder_.getMessageOrBuilder();
        } else {
          return inventoryMonthAmount_ == null ?
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.getDefaultInstance() : inventoryMonthAmount_;
        }
      }
      /**
       * <code>.InventoryMonthAmount inventoryMonthAmount = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder> 
          getInventoryMonthAmountFieldBuilder() {
        if (inventoryMonthAmountBuilder_ == null) {
          inventoryMonthAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder>(
                  getInventoryMonthAmount(),
                  getParentForChildren(),
                  isClean());
          inventoryMonthAmount_ = null;
        }
        return inventoryMonthAmountBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetInventoryMonthAmountRespon)
    }

    // @@protoc_insertion_point(class_scope:GetInventoryMonthAmountRespon)
    private static final com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon();
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInventoryMonthAmountRespon>
        PARSER = new com.google.protobuf.AbstractParser<GetInventoryMonthAmountRespon>() {
      public GetInventoryMonthAmountRespon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetInventoryMonthAmountRespon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInventoryMonthAmountRespon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInventoryMonthAmountRespon> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.GetInventoryMonthAmountRespon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InventoryMonthAmountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InventoryMonthAmount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>int64 sumOfmoney = 1;</code>
     */
    long getSumOfmoney();
  }
  /**
   * Protobuf type {@code InventoryMonthAmount}
   */
  public  static final class InventoryMonthAmount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InventoryMonthAmount)
      InventoryMonthAmountOrBuilder {
    // Use InventoryMonthAmount.newBuilder() to construct.
    private InventoryMonthAmount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InventoryMonthAmount() {
      sumOfmoney_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InventoryMonthAmount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sumOfmoney_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_InventoryMonthAmount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_InventoryMonthAmount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder.class);
    }

    public static final int SUMOFMONEY_FIELD_NUMBER = 1;
    private long sumOfmoney_;
    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>int64 sumOfmoney = 1;</code>
     */
    public long getSumOfmoney() {
      return sumOfmoney_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sumOfmoney_ != 0L) {
        output.writeInt64(1, sumOfmoney_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sumOfmoney_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sumOfmoney_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount)) {
        return super.equals(obj);
      }
      com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount other = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount) obj;

      boolean result = true;
      result = result && (getSumOfmoney()
          == other.getSumOfmoney());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUMOFMONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSumOfmoney());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InventoryMonthAmount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InventoryMonthAmount)
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_InventoryMonthAmount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_InventoryMonthAmount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.class, com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.Builder.class);
      }

      // Construct using com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sumOfmoney_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.internal_static_InventoryMonthAmount_descriptor;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getDefaultInstanceForType() {
        return com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.getDefaultInstance();
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount build() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount buildPartial() {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount result = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount(this);
        result.sumOfmoney_ = sumOfmoney_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount) {
          return mergeFrom((com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount other) {
        if (other == com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount.getDefaultInstance()) return this;
        if (other.getSumOfmoney() != 0L) {
          setSumOfmoney(other.getSumOfmoney());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sumOfmoney_ ;
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int64 sumOfmoney = 1;</code>
       */
      public long getSumOfmoney() {
        return sumOfmoney_;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int64 sumOfmoney = 1;</code>
       */
      public Builder setSumOfmoney(long value) {
        
        sumOfmoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int64 sumOfmoney = 1;</code>
       */
      public Builder clearSumOfmoney() {
        
        sumOfmoney_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:InventoryMonthAmount)
    }

    // @@protoc_insertion_point(class_scope:InventoryMonthAmount)
    private static final com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount();
    }

    public static com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InventoryMonthAmount>
        PARSER = new com.google.protobuf.AbstractParser<InventoryMonthAmount>() {
      public InventoryMonthAmount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InventoryMonthAmount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InventoryMonthAmount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryMonthAmount> getParserForType() {
      return PARSER;
    }

    public com.yhglobal.gongxiao.inventory.inventorymonthamount.microservice.InventoryMonthAmountStructure.InventoryMonthAmount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInventoryMonthAmountRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInventoryMonthAmountRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInventoryMonthAmountRespon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInventoryMonthAmountRespon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryMonthAmount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryMonthAmount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032inventorymonthamount.proto\032\037gongxiao.g" +
      "lobal.structure.proto\"e\n\036GetInventoryMon" +
      "thAmountRequest\022\035\n\trpcHeader\030\001 \001(\0132\n.Rpc" +
      "Header\022\021\n\tprojectId\030\002 \001(\003\022\021\n\tyearMonth\030\003" +
      " \001(\t\"T\n\035GetInventoryMonthAmountRespon\0223\n" +
      "\024inventoryMonthAmount\030\001 \001(\0132\025.InventoryM" +
      "onthAmount\"*\n\024InventoryMonthAmount\022\022\n\nsu" +
      "mOfmoney\030\001 \001(\0032{\n\033InventoryMonthAmoundSe" +
      "rvice\022\\\n\027getInventoryMonthAmount\022\037.GetIn" +
      "ventoryMonthAmountRequest\032\036.GetInventory",
      "MonthAmountRespon\"\000Bb\nAcom.yhglobal.gong" +
      "xiao.inventory.inventorymonthamount.micr" +
      "oserviceB\035InventoryMonthAmountStructureb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor(),
        }, assigner);
    internal_static_GetInventoryMonthAmountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetInventoryMonthAmountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInventoryMonthAmountRequest_descriptor,
        new java.lang.String[] { "RpcHeader", "ProjectId", "YearMonth", });
    internal_static_GetInventoryMonthAmountRespon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetInventoryMonthAmountRespon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInventoryMonthAmountRespon_descriptor,
        new java.lang.String[] { "InventoryMonthAmount", });
    internal_static_InventoryMonthAmount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_InventoryMonthAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryMonthAmount_descriptor,
        new java.lang.String[] { "SumOfmoney", });
    com.yhglobal.gongxiao.microservice.GongxiaoRpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
